// src/components/list/meals.tsx
import MealCard, { MealCardProps } from '$components/card/meal'

const Meals: React.FC<MealsProps> = ({ meals, className }) => {
  return (
    <article
      role="article"
      className={`flex justify-center items-stretch flex-wrap gap-3 container mb-8 ${
        className ?? ''
      }`.trim()}
      // className="grid grid-cols-2 grid-rows-5 gap-2"
    >
      {meals.map(meal => {
        return <MealCard key={meal['idMeal']} meal={meal} />
      })}
    </article>
  )
}

export interface MealsProps {
  meals: MealCardProps['meal'][]
  className?: string
}

export default Meals

// web/src/lib/components/list/meals.svelte
<script lang="ts">
	import MealCard from '../card/meal.svelte';
	import type { MealCardProps } from '../card/meal';
	import { onMount } from 'svelte';

	let meals: MealCardProps['meal'][];
	let clazz: string = '';

	export { meals, clazz as class };

	onMount(() => {
		console.log(meals);
	});
</script>

<article class={`flex justify-center items-stretch flex-wrap gap-3 container mb-8 ${clazz}`.trim()}>
	{#each meals as meal (meal['id'])}
		<MealCard {meal} />
	{/each}
</article>
