// web/src/lib/components/card/category.svelte
<script lang="ts">
	import Image from 'svelte-image';

	import CategoryLink from '$lib/components/link/category.svelte';
	import type { ICategory } from '$lib/types/category';

	export let category: ICategory;
</script>

<CategoryLink
	key={category.id}
	category={category.name}
	class="card card-compact shadow-md p-2 bg-base-100 hover:shadow-lg transition-shadow flex justify-end relative aspect-square w-80"
>
	<Image src={category.thumb} alt={`Category - ${category.name}`} object-position="center top" />
	<div role="contentinfo" class="card-body absolute bottom-0">
		<h2 class="mb-2">{category.name}</h2>
		<p role="definition" class="mb-0 line-clamp-3">
			{@html category.description}
		</p>
	</div>
</CategoryLink>

// src/components/card/category.tsx
import Image from 'next/image'

import CategoryLink from '$components/link/category'
import type { ICategory } from 'types/category'

const CategoryCard: React.FC<{ category: ICategory }> = ({ category }) => {
  return (
    <CategoryLink
      key={category.idCategory}
      category={category.strCategory}
      className="card card-compact shadow-md p-2 bg-base-100 hover:shadow-lg transition-shadow flex justify-end relative aspect-square w-80"
    >
      <Image
        src={category.strCategoryThumb}
        alt={`Category - ${category.strCategory}`}
        layout="fill"
        objectFit="contain"
        objectPosition="center top"
      />
      <div role="contentinfo" className="card-body absolute bottom-0">
        <h2 className="mb-2">{category.strCategory}</h2>
        <p role="definition" className="mb-0 line-clamp-3">
          {category.strCategoryDescription}
        </p>
      </div>
    </CategoryLink>
  )
}

export default CategoryCard
