// web/src/routes/meal/category/index.svelte
<script lang="ts" context="module">
	import type { Load } from '@sveltejs/kit';

	// export const prerender = true;

	export const load: Load = async ({ fetch }) => {
		const res = await fetch('/api/meal/category');
		const { categories } = await res.json();

		return {
			props: {
				categories
			},
			cache: {
				maxage: 60 * 60 * 24 // 1 day
			},
			dependencies: ['/api/meal/category']
		};
	};
</script>

<script lang="ts">
	import { MetaTags } from 'svelte-meta-tags';
	import Typewriter from 'svelte-typewriter';

	import CategoryCard from '$lib/components/card/category.svelte';
	import type { ICategory } from '$lib/types/category';

	export let categories: ICategory[];
</script>

<main class="flex justify-center">
	<MetaTags
		title="Categories | COOKit"
		description={`${categories.length} different meal categories to choose from!`}
		additionalLinkTags={[
			{ rel: 'icon', href: '/images/garnish.png' },
			{ rel: 'alternate', href: '/meal/category/rss.xml', type: 'application/rss+xml' }
		]}
		openGraph={{
			title: 'Categories | COOKit',
			description: `${categories.length} different meal categories to choose from!`,
			url: 'https://cookingit.netlify.app/category',
			images: [
				{
					url: '/demos/categories.png',
					alt: 'Categories | COOKit'
				}
			]
		}}
	/>
	<section class="container mb-12">
		<h1 class="text-center my-6">Categories</h1>
		<!-- TODO: Write description for category page -->
		{#key categories.length}
			<Typewriter>
				<p>
					{categories.length + ' different meal categories to choose from!'}
				</p>
			</Typewriter>
		{/key}

		<article class="flex justify-center items-stretch flex-wrap gap-3 container">
			{#each categories as category (category.id)}
				<CategoryCard {category} />
			{/each}
		</article>
	</section>
</main>

// src/pages/meal/category/index.tsx
import Head from 'next/head'
import type { GetStaticProps, NextPage } from 'next'

import { mealdb } from '$utils/axios'
import CategoryCard from '$components/card/category'
import type { ICategory } from 'types/category'
import { NextSeo } from 'next-seo'

const CategoryPage: NextPage<CategoryPageProps> = ({ categories }) => {
  return (
    <main className="flex justify-center">
      <NextSeo
        title="Categories | COOKit"
        description={`${categories.length} different meal categories to choose from!`}
        additionalLinkTags={[{ rel: 'icon', href: '/images/garnish.png' }]}
        openGraph={{
          title: 'Categories | COOKit',
          description: `${categories.length} different meal categories to choose from!`,
          url: 'https://cookingit.netlify.app/category',
          images: [
            {
              url: '/demos/categories.png',
              alt: 'Categories | COOKit',
            },
          ],
        }}
      />
      <section className="container mb-12">
        <h1 className="text-center my-6">Categories</h1>

        {/* TODO: Write description for category page */}
        <p>{categories.length} different meal categories to choose from!</p>

        <article className="flex justify-center items-stretch flex-wrap gap-3 container">
          {categories.map(category => {
            return (
              <CategoryCard key={category.idCategory} category={category} />
            )
          })}
        </article>
      </section>
    </main>
  )
}

CategoryPage.displayName = 'Category'

export const getStaticProps: GetStaticProps<CategoryPageProps> = async ctx => {
  const res = await mealdb.get('/categories.php')
  return {
    props: {
      categories: res.data['categories'],
    },
    revalidate: 60 * 60 * 24,
  }
}

export interface CategoryPageProps {
  categories: ICategory[]
}

export default CategoryPage
